name: test
description: "Build, test, and dry-run semver-tags on pull requests"
triggers:
  events:
    - pull_request_opened
    - pull_request_updated
  branches:
    - main
paths:
  include:
    - "cmd/**"
    - "core/**"
    - "test/**"
    - "Dockerfile"
    - "go.mod"
    - "go.sum"
job:
  image: golang:1.20
  command: |
    set -e
    git clone --branch "${REACTORCIDE_PR_REF}" "${REACTORCIDE_SOURCE_URL}" /workspace
    cd /workspace
    echo "=== Building ==="
    go build -race
    echo "=== Testing ==="
    go test -v ./...
    echo "=== Semver Tags Dry Run ==="
    ./semver-tags run --dry_run --output_json
  timeout: 1800
  priority: 10
  raw_command: true
environment:
  CGO_ENABLED: "1"
