name: Pull Request
on:
  pull_request:
    branches:
      - main
    paths:
      - 'cmd/**'
      - 'core/**'
      - 'test/**'
      - Dockerfile
      - 'go.mod'
      - 'go.sum'
jobs:
  conventional-commits-pr:
    if: github.event.pull_request.draft == false
    name: Validate Conventional Commits PR
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-dump-context@v2
      - uses: catalystsquad/action-validate-conventional-commits-pr@v1
  ensure-compile:
    if: github.event.pull_request.draft == false
    name: Ensure project compiles
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-dump-context@v2
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go With Caching
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version: "1.20"
      - name: Compile
        shell: bash
        run: |
          go build -race
  test:
    needs:
      - ensure-compile
    name: Test
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Dump Context
        uses: crazy-max/ghaction-dump-context@v2
      - name: Run Tests
        working-directory: ./
        run: |
          echo $(pwd)
          ls -al .
          go test -v ./...
      - name: semver-tags
        run: |
          ./semver-tags run --dry_run --github_action 
      - name: tags-output
        run: |
          echo "${{ steps.semver-tags.outputs }}"
