name: Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'cmd/**'
      - 'core/**'
      - 'test/**'
      - 'go.mod'
      - 'go.sum'
jobs:
  release:
    runs-on: ubuntu-latest
    name: Release 
    steps:
      - uses: crazy-max/ghaction-dump-context@v2
  ensure-compile:
    if: github.event.pull_request.draft == false
    name: Ensure project compiles
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-dump-context@v2
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go With Caching
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version: "1.20"
      - name: Compile
        shell: bash
        run: |
          go build -race
      - name: Semver Tags
        id: semver-tags
        working-directory: ./
        run: |
          ./semver-tags run --github_action 
      - name: Make Release
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.AUTOMATION_PAT }}
          goos: linux
          goarch: amd64
          build_flags: -race
          release_name: ${{ steps.semver-tags.outputs.new_release_version }}


