name: Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'cmd/**'
      - 'core/**'
      - 'test/**'
      - 'go.mod'
      - 'go.sum'
jobs:
  release:
    if: github.event.pull_request.merged == true
    name: Make a Release
    runs-on: ubuntu-latest
    steps:
      - name: Dump Context
        uses: crazy-max/ghaction-dump-context@v2
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go With Caching
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version: "1.20"
      - name: Compile
        shell: bash
        run: |
          go build -race
      - name: Semver Tags
        id: semver-tags
        working-directory: ./
        run: |
          ./semver-tags run --github_action | yq -P -o=json "."
      - name: Make Release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME: ${{ steps.semver-tags.outputs.new_release_git_tag }}
        run: |
          ./.github/scripts/make_release.sh "${RELEASE_NAME}"
