name: Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'cmd/**'
      - 'core/**'
      - 'test/**'
      - 'go.mod'
      - 'go.sum'
jobs:
  release:
    runs-on: ubuntu-latest
    name: Release 
    steps:
      - uses: crazy-max/ghaction-dump-context@v2
  ensure-compile:
    if: github.event.pull_request.draft == false
    name: Ensure project compiles
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-dump-context@v2
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go With Caching
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version: "1.20"
      - name: Compile
        shell: bash
        run: |
          go build -race
      - name: Semver Tags
        id: semver-tags
        working-directory: ./
        run: |
          ./semver-tags run --github_action 
      - name: Make Release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secretes.GITHUB_TOKEN }}
          RELEASE_NAME: ${{ steps.semver-tags.outputs.new_release_version }}
        run: |
          tar -cvzf semver-tags.tar.gz ./semver-tags
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer <YOUR-TOKEN>"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            ${{ vars.GITHUB_API_URL }}/repos/${{ vars.GITHUB_ACTION_REPOSITORY  }}/releases \
            -d '{"tag_name":"${RELEASE_NAME}","target_commitish":"main","name":"${RELEASE_NAME}","body":"Released by Github Action","draft":false,"prerelease":false,"generate_release_notes":false}'
